name: Deploy to VPS

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Deploy to VPS
        run: |
          ssh user@your-vps "docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest"
          ssh user@your-vps "docker stop myapp || true && docker rm myapp || true"
          ssh user@your-vps "docker run -d -p 8080:80 --name myapp ${{ secrets.DOCKER_USERNAME }}/myapp:latest"
